PROJECT(NLM CXX C)

CMAKE_MINIMUM_REQUIRED(VERSION 3.10)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

IF(NOT MINC_TOOLKIT_BUILD)
  SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/cmake-modules")

  FIND_PACKAGE(LIBMINC REQUIRED)
  INCLUDE( ${LIBMINC_USE_FILE} )
  FIND_PACKAGE(GSL REQUIRED)
  FIND_PACKAGE(FFTW3F REQUIRED)
  FIND_PACKAGE(NIFTI REQUIRED)
ENDIF(NOT MINC_TOOLKIT_BUILD)

INCLUDE_DIRECTORIES( ${GSL_INCLUDE_DIR} ${FFTW3F_INCLUDE_DIRS} ${NIFTI_INCLUDE_DIR} ${ZNZ_INCLUDE_DIR} )

ADD_SUBDIRECTORY(src)
